env:
    global:
        - PACKAGE="sublack" # Package name
        - SUBLIME_TEXT_VERSION="3"
        # use UNITTESTING_TAG to specific tag of UnitTesting
        # - UNITTESTING_TAG="master"

# mutliple os matrix
# https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)
matrix:
    include:
        - os: linux
          language: python
          python: 3.6
        - os: osx
          language: generic

services:
    # Starts a graphical environment
    - xvfb


before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap
    # - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    #         brew update;
    #   fi
    # brew install python;
    # || brew upgrade python;
    - pip3 install black[d]
    - pip3 install requests
    - pip3 install pre-commit
    # - pip3 install black requests
    # install Package Control and package dependencies
    - sh travis.sh install_package_control

script:
    - which python
    - which python
    - bash -ilc env
    # run tests with test coverage report
    - sh travis.sh run_tests --coverage
    # testing syntax_test files
    # - sh travis.sh run_syntax_tests

after_success:
    # remove the following if `coveralls` is not needed
    - pip3 install codecov;
    - codecov

notifications:
    email: false
